Created db package to handle database with gorm
scienceandcode/habits-todo-backend pull request #7
Opened 2024-12-13 18:39 UTC by MatheusGardin

## Impacto
Permite a conexão com o banco de dados utilizando o ORM [GORM.](https://gorm.io)

```
git pull && git checkout setup-gorm
```
```
go run cmd/habits-todo-backend/main.go
```

2024-12-13 18:53 UTC, Matheus-Lara commented
@MatheusGardin é pra estar closed mesmo?

2024-12-13 19:16 UTC, MatheusGardin commented
> @MatheusGardin é pra estar closed mesmo? Posso revisar?

@Matheus-Lara Eu tinha fechado por querer mesmo, agora pode revisar!!

2024-12-13 19:58 UTC, Matheus-Lara commented
@MatheusGardin beleza, a noite irei revisar! Obrigado

2024-12-14 01:21 UTC, Matheus-Lara requested changes

2024-12-14 01:21 UTC, Matheus-Lara commented on internal/api/repository/base_repository_test.go
> +package repository_test
porque o package se chama `repository_test` se ele não está em uma pasta com esse nome?

2024-12-14 01:21 UTC, Matheus-Lara commented on internal/api/repository/base_repository.go
Não acho que repository deveria estar dentro de `api`, se futuramente criarmos alguma ação assíncrona como jobs, ou até mensageria no projeto. o repository pode ser usado para fazer consultas em outros contextos. Cria esse diretório ao lado de API e não dentro.

2024-12-14 01:21 UTC, Matheus-Lara commented on pkg/db/db.go
me parece fazer mais sentido esse arquivo estar no diretório `intenal/db` A conexão com banco de dados deste projeto não é um pkg reutilizável e exportável para projetos externos, então não deve ficar público.

2024-12-14 01:23 UTC, Matheus-Lara commented on internal/api/repository/base_repository_test.go
> +package repository_test
normalmente a gente mantém os packages com o próprio nome do diretório

2024-12-14 01:40 UTC, Matheus-Lara commented on internal/api/repository/base_repository_test.go
Esse log tá correto?
![image](https://github.com/user-attachments/assets/19d21abe-e38a-4baa-8a1e-a42419df69ea)

2024-12-17 22:26 UTC, MatheusGardin commented on internal/api/repository/base_repository_test.go
> +package repository_test
a398169aecb89de6099153be9bbacadcc4e75b4c

2024-12-17 22:27 UTC, MatheusGardin commented on internal/api/repository/base_repository.go
Feito!!

2024-12-17 22:31 UTC, MatheusGardin commented on pkg/db/db.go
a45c053a108fbc5377c7c7d79d56d27e2e779e7c

2024-12-17 22:38 UTC, MatheusGardin commented on internal/api/repository/base_repository_test.go
Sim esse é o log do `FindByID`, não é um erro

2024-12-17 23:27 UTC, Matheus-Lara approved these changes
Brabo!

2024-12-17 23:27 UTC, merged